server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Workintech-Sprint19-C1
spring.datasource.username=postgres
spring.datasource.password=852456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=fsweb
spring.jpa.show-sql=true